### ISSUE TITLE
 throw new Error('Could not encode')

### ISSUE THREAD

**Issue by qiulang** [darrachequesne/notepack#29]
When add socket.io/admin-ui, I hit `Error('Could not encode');`

```
const { instrument } = require("@socket.io/admin-ui");
instrument(io, {
  auth: {
    type: "basic",
    username: "xxx",
    password: "xxxxxx"
  },
});
```

```
.../node_modules/notepack.io/lib/encode.js:256
      throw new Error('Could not encode');
            ^
Error: Could not encode
    at _encode (.../node_modules/notepack.io/lib/encode.js:256:13)
    at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
    at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
    at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
    at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
    at Object.encode (.../node_modules/notepack.io/lib/encode.js:261:41)
    at RedisAdapter.broadcast (.../node_modules/socket.io-redis/dist/index.js:313:33)
    at BroadcastOperator.emit (.../node_modules/socket.io/dist/broadcast-operator.js:109:22)
    at Namespace.emit (.../node_modules/socket.io/dist/namespace.js:170:73)
    at Socket.<anonymous> (.../node_modules/@socket.io/admin-ui/dist/index.js:284:36)
```

**Comment by darrachequesne** [comment]
@qiulang hi! `Could not encode` means the encoder encountered something it was not able to encode (for example, a Set). What are you trying to send? Could you please provide an example?

**Comment by qiulang** [comment]
@darrachequesne I did not see your reply for some days. Not sure if you find the cause.

So I create a project (based on Socket.IO Fiddle) to reproduce the issue https://github.com/qiulang/socket.io-admin-ui, please take a look
